# Generated by Django 3.2.16 on 2022-10-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('pvz', models.CharField(choices=[('PVZ1', 'ПВЗ-1'), ('PVZ2', 'ПВЗ-2'), ('PVZ3', 'ПВЗ-3'), ('PVZ4', 'ПВЗ-4'), ('PVZ5', 'ПВЗ-5'), ('PVZ6', 'ПВЗ-6'), ('PVZ7', 'ПВЗ-7'), ('PVZ8', 'ПВЗ-8')], default=None, max_length=4)),
                ('service', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=50)),
                ('the_original', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=3)),
                ('the_copy', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=3)),
                ('absent', models.CharField(max_length=150)),
                ('rate', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('document', models.CharField(max_length=150)),
                ('edo', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=100)),
                ('notes', models.TextField(max_length=250)),
            ],
        ),
    ]
