# Generated by Django 3.2.16 on 2022-12-17 12:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2022, 12, 17))),
                ('hours', models.IntegerField()),
                ('pvz', models.CharField(blank=True, choices=[('PVZ1', 'ПВЗ-1'), ('PVZ2', 'ПВЗ-2'), ('PVZ3', 'ПВЗ-3'), ('PVZ4', 'ПВЗ-4'), ('PVZ5', 'ПВЗ-5'), ('PVZ6', 'ПВЗ-6'), ('PVZ7', 'ПВЗ-7'), ('PVZ8', 'ПВЗ-8')], default=None, max_length=4, verbose_name='ПВЗ')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя работника')),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графики',
            },
        ),
    ]
